version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: wd_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_database.sql:/docker-entrypoint-initdb.d/init_database.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "postgres", "-d", "postgres", ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: wd_app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["python", "main.py"]

volumes:
  postgres_data:
    driver: local